name: medicos
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  google_sign_in: ^6.3.0
  flutter_facebook_auth: ^6.1.1
  sign_in_with_apple: ^7.0.1
  provider: ^6.1.2
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.1
  cloud_firestore: ^5.6.6
  location: ^8.0.0
  geocoding: ^3.0.0
  flutter_google_maps_webservices: ^1.1.1
  flutter_svg: ^2.0.9
  firebase_messaging: ^15.2.5
  fluttertoast: ^8.2.12
  google_fonts: ^6.2.1
  flutter_timezone: ^4.1.0
  intl: ^0.20.2
  lucide_icons: ^0.256.0
  flutter_local_notifications: ^19.0.0
  timezone: ^0.10.0
  speech_to_text: ^7.0.0
  flutter_tts: ^4.2.2
  permission_handler: ^12.0.0+1
  image_picker: ^1.1.2
  file_picker: ^10.1.2
  firebase_storage: ^12.4.5
  path_provider: ^2.1.5
  open_file: ^3.5.10
  android_wake_lock: ^1.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # Remove the fonts section since we'll use google_fonts package
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700


