name: medicos
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.7.0 <4.0.0'  # Corrected SDK version

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.2.2
  provider: ^6.1.2
  geolocator: ^13.0.2
  google_maps_flutter: ^2.10.1
  cloud_firestore: ^5.6.4
  location: ^8.0.0
  geocoding: ^3.0.0
  flutter_google_maps_webservices: ^1.1.1
  flutter_svg: ^2.0.9
  firebase_messaging: ^15.2.4
  fluttertoast: ^8.2.12
  google_fonts: ^6.2.1
  flutter_timezone: ^4.1.0
  intl: ^0.20.2
  lucide_icons: ^0.256.0
  flutter_local_notifications: ^19.0.0
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true


#  assets:
#    - assets/images/
#    - assets/icons/

  fonts:
    - family: Poppins
      fonts:
#        - asset: assets/fonts/Poppins-Regular.ttf
#        - asset: assets/fonts/Poppins-Medium.ttf
#          weight: 500
##        - asset: assets/fonts/Poppins-SemiBold.ttf
#          weight: 600


